global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
    # for redirection
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
providers: # https://doc.traefik.io/traefik/reference/install-configuration/providers/docker/
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
